### ISSUE TITLE
Should we include the GDP breakdown by 'BusinessType'?

### ISSUE THREAD

**Issue by arturoboquin** [UBC-MDS/New_Businesses_Survival_Prediction#13]

**Comment by arturoboquin** [comment]
Using the total GDP we have a good estimator. Adding the breakdown in separate variables might help, but in the case we need to match the BusinessType in the Vancouver Dataset and the one in external data (different sources). What do yo guys think, do we try it now or in the future?

**Comment by Prabh95** [comment]
Using the total GDP we have a good estimator. Adding the breakdown in separate variables might help, but in the case we need to match the BusinessType in the Vancouver Dataset and the one in external data (different sources). What do yo guys think, do we try it now or in the future?

**Comment by beth-ouyang** [comment]
In my opinoin, it might be hard to manually map the `BusinessType` in **business-license dataset** to the related industries in the **GDP dataset**. Guess we can just consider the overall GDP performance in this project?

**Comment by weiranzhao97** [comment]
I think the overall GDP is fine since we are aiming to understand how broader economic conditions affect business units (as other features do like 'ConsumerPriceValue', 'EmploymentValue'). Using general GDP can provide good context in this case.

**Comment by arturoboquin** [comment]
Let's follow that line
